name: Electron Build and Release

on:
  push:
    branches: [main]
    # Only trigger when commit message contains "build"
    if: contains(github.event.head_commit.message, 'build')
  # Optional: Add manual trigger
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v-0.0.1'

env:
  NODE_VERSION: '20'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    strategy:
      fail-fast: false  # Continue with other builds if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            build-command: build-win
            artifact-path: 'package/win-unpacked/*.exe'
          - os: macos-latest
            build-command: build-mac
            artifact-path: 'package/mac/*.dmg'
          - os: ubuntu-latest
            build-command: build-linux
            artifact-path: 'package/linux/*.AppImage'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'  # Enable npm caching

      - name: Install dependencies
        run: |
          npm ci  # More reliable than npm install for CI environments
        
      - name: Build Electron app
        run: |
          npm run build
          npm run ${{ matrix.build-command }}
        shell: bash

      # Cache build artifacts
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            package/
            dist/
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.event.inputs.version || 'v-0.0.1' }}
          name: Release ${{ github.event.inputs.version || 'v-0.0.1' }}
          body: |
            ## What's Changed
            ${{ github.event.head_commit.message }}
            
            ## Build Information
            - OS: ${{ matrix.os }}
            - Node Version: ${{ env.NODE_VERSION }}
            - Commit: ${{ github.sha }}
          artifacts: ${{ matrix.artifact-path }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      # Optional: Cleanup cache
      - name: Cleanup
        if: always()
        run: |
          npm cache clean --force
          rm -rf node_modules
        shell: bash